project_id = "chojxtvzspqqzsmwcbul"

[functions.process-feedback]
verify_jwt = false

[functions.deck-recommendations]
verify_jwt = false

[functions.fetch-moxfield-deck]
verify_jwt = false

[functions.deck-categorize]
verify_jwt = false

[functions.deck-suggest]
verify_jwt = false